megaline:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: megaline_admin
      password: megaline_secure_pwd
      dbname: megaline_dwh
      schema: public
      threads: 4
